export default {
    items: [
        {
            id: 1,
            label: "Hello",
            traduction: "Bonjour",
            flagTarget: "jp",
            flagOrigin: "uk",
            author: "Ludo",
            type: "audio",
            avatar: "https://randomuser.me/api/portraits/men/75.jpg",
        },
        {
            id: 2,
            label: "how are you",
            traduction: "comment ça va",
            flagTarget: "fr",
            flagOrigin: "uk",
            author: "Ludo",
            type: "audio",
            avatar: "https://randomuser.me/api/portraits/men/74.jpg",
        },
        {
            id: 3,
            pseudo: "Axel",
            type: "member",
        },
        {
            id: 4,
            pseudo: "Ludo",
            type: "member",
        },
        {
            id: 5,
            pseudo: "Gautier",
            type: "member",
        },
        {
            id: 6,
            pseudo: "Quentin",
            type: "member",
        },
        {
            id: 7,
            pseudo: "Sacha",
            type: "member",
        },
        {
            id: 8,
            label: "how are you",
            traduction: "como você està ?",
            flagTarget: "pt",
            flagOrigin: "uk",
            author: "Ludo",
            type: "audio",
            avatar: "https://randomuser.me/api/portraits/men/73.jpg",
        },
        {
            id: 9,
            label: "how are you",
            traduction: "como estas ?",
            flagTarget: "es",
            flagOrigin: "uk",
            author: "Ludo",
            type: "audio",
            avatar: "https://randomuser.me/api/portraits/men/72.jpg",
        },
    ],
};
